### ISSUE TITLE
Remove the German translation

### ISSUE THREAD

**Issue by Omikhleia** [Omikhleia/sindict#1]
For the 2.0-final cleanup, I suggest removing the German translations from the core XML lexicon... (they are already excluded in the default HTML build in 2.0a5):
- Let's be honest, they were never really on par with the rest of the project, despite the past efforts
- They weren't maintained even when the project was considered still somehow publicly active (2006-2008).
- The contacts from that time have at best shifted interests

I'm of course biased on this issue (let's not say more than that here...), and I don't want to awake the old beasts.

But it would be quickly doable by script, so...

**Comment by BenTalagan** [comment]
Maintaining so many locales is really a challenge... can even be a project killer in some circumstances! Maybe for the sake of mind comfort, they could be extracted and put aside instead of dropped? But since it would probably mean generating a sub-xml with german-only stuff, it's probably not even worth doing it, since for a future reintegration one can probably start from the full xml version preceding the drop. So ... ⚔️  ?
